apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: commerce-coach
  namespace: commerce-coach
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: commerce-coach
