import type { KnowledgeItem } from './knowledgeBase';

type AdditionalFaq = {
  number: number;
  domain: string;
  keywords: string[];
  question: string;
  answer: string;
  questionBn: string;
  answerBn: string;
  status?: KnowledgeItem['status'];
  screenshotIds?: string[];
  source: string;
};

function faq({ number, questionBn, answerBn, status = 'live', ...item }: AdditionalFaq): KnowledgeItem {
  return {
    id: `merchant-faq-${String(number).padStart(3, '0')}`,
    feature: item.question.replace(/\?$/, ''),
    ...item,
    status,
    translations: { bn: { question: questionBn, answer: answerBn } },
  };
}

/**
 * Additional customer questions derived from the Product Memo. Each answer stays
 * within documented behavior and links to a focused visual guide where available.
 */
export const ADDITIONAL_MERCHANT_FAQ_ITEMS = [
  faq({
    number: 70,
    domain: 'signup',
    keywords: ['otp', 'verification code', 'signup', 'ওটিপি', 'কোড'],
    question: 'What should I do if I do not receive the signup OTP?',
    answer: 'Check that the phone number is correct and wait briefly before requesting another OTP. Also check whether SMS is being blocked. If repeated attempts still fail, contact Pathao support with the phone number you used to sign up.',
    questionBn: 'সাইনআপের OTP না পেলে কী করব?',
    answerBn: 'ফোন নম্বরটি ঠিক আছে কি না যাচাই করুন এবং নতুন OTP চাওয়ার আগে কিছুক্ষণ অপেক্ষা করুন। SMS ব্লক হচ্ছে কি না সেটিও দেখুন। বারবার চেষ্টা করেও না পেলে যে নম্বর দিয়ে সাইনআপ করছেন সেটি দিয়ে পাঠাও সাপোর্টে যোগাযোগ করুন।',
    screenshotIds: ['signup-001'],
    source: 'Product Memo §7.1',
  }),
  faq({
    number: 71,
    domain: 'dashboard',
    keywords: ['dashboard', 'navigation', 'menu', 'ড্যাশবোর্ড', 'মেনু'],
    question: 'How is the Pathao Commerce dashboard organized?',
    answer: 'Use the left navigation to move between products, inventory, orders, chats, channels, delivery, finance, and settings. The dashboard home summarizes important business activity so you can decide what needs attention first.',
    questionBn: 'পাঠাও কমার্স ড্যাশবোর্ড কীভাবে সাজানো?',
    answerBn: 'বাম পাশের নেভিগেশন থেকে প্রোডাক্ট, ইনভেন্টরি, অর্ডার, চ্যাট, চ্যানেল, ডেলিভারি, ফাইন্যান্স ও সেটিংসে যেতে পারবেন। ড্যাশবোর্ড হোমে গুরুত্বপূর্ণ ব্যবসায়িক কার্যক্রমের সারাংশ দেখা যায়, তাই কোন কাজ আগে দরকার তা দ্রুত বুঝতে পারবেন।',
    source: 'Product Memo §7.0',
  }),
  faq({
    number: 72,
    domain: 'dashboard',
    keywords: ['notification', 'alert', 'bell', 'নোটিফিকেশন', 'অ্যালার্ট'],
    question: 'Where can I see important notifications?',
    answer: 'Open the notification area from the dashboard header. It brings important account and business updates together; select a notification to review the related item or action.',
    questionBn: 'গুরুত্বপূর্ণ নোটিফিকেশন কোথায় দেখব?',
    answerBn: 'ড্যাশবোর্ড হেডার থেকে নোটিফিকেশন অংশ খুলুন। এখানে গুরুত্বপূর্ণ অ্যাকাউন্ট ও ব্যবসায়িক আপডেট একসাথে থাকে; সংশ্লিষ্ট তথ্য বা কাজ দেখতে নোটিফিকেশনটি নির্বাচন করুন।',
    source: 'Product Memo §7.0',
  }),
  faq({
    number: 73,
    domain: 'settings',
    keywords: ['business settings', 'account settings', 'profile', 'সেটিংস', 'প্রোফাইল'],
    question: 'Where can I update my business and account settings?',
    answer: 'Open Settings from the dashboard navigation. Review the available business and account sections there, then update the relevant details and save your changes.',
    questionBn: 'বিজনেস ও অ্যাকাউন্ট সেটিংস কোথায় আপডেট করব?',
    answerBn: 'ড্যাশবোর্ড নেভিগেশন থেকে Settings খুলুন। সেখানে থাকা বিজনেস ও অ্যাকাউন্ট অংশ থেকে প্রয়োজনীয় তথ্য আপডেট করে পরিবর্তনগুলো সেভ করুন।',
    source: 'Product Memo §7.0',
  }),
  faq({
    number: 74,
    domain: 'dashboard',
    keywords: ['global search', 'search', 'find', 'সার্চ', 'খুঁজুন'],
    question: 'What can I find with global search?',
    answer: 'Use the dashboard search to quickly find supported business records without opening each section one by one. Enter a specific identifier or useful keyword, then open the matching result.',
    questionBn: 'গ্লোবাল সার্চ দিয়ে কী খুঁজে পাওয়া যায়?',
    answerBn: 'প্রতিটি সেকশন আলাদাভাবে না খুলে ড্যাশবোর্ড সার্চ থেকে সমর্থিত ব্যবসায়িক রেকর্ড দ্রুত খুঁজতে পারবেন। নির্দিষ্ট আইডি বা উপযোগী কীওয়ার্ড লিখে মিল পাওয়া ফলাফল খুলুন।',
    source: 'Product Memo §7.0',
  }),
  faq({
    number: 75,
    domain: 'dashboard',
    keywords: ['mobile browser', 'responsive', 'phone', 'মোবাইল', 'ব্রাউজার'],
    question: 'Can I use Pathao Commerce from a mobile browser?',
    answer: 'Yes. Pathao Commerce is designed to work in a mobile browser, although wide tables and complex management tasks may be easier on a larger screen.',
    questionBn: 'মোবাইল ব্রাউজার থেকে পাঠাও কমার্স ব্যবহার করা যাবে?',
    answerBn: 'হ্যাঁ। পাঠাও কমার্স মোবাইল ব্রাউজারে ব্যবহার করা যায়, তবে বড় টেবিল বা জটিল ম্যানেজমেন্টের কাজ বড় স্ক্রিনে আরও সুবিধাজনক হতে পারে।',
    source: 'Product Memo §7.0',
  }),
  faq({
    number: 76,
    domain: 'warehouse',
    keywords: ['warehouse', 'add warehouse', 'location', 'ওয়্যারহাউস', 'ঠিকানা'],
    question: 'How do I add another warehouse?',
    answer: 'Open the warehouse section, choose to add a warehouse, and enter its name, contact details, and full address. Save it after reviewing the information.',
    questionBn: 'আরেকটি ওয়্যারহাউস কীভাবে যোগ করব?',
    answerBn: 'ওয়্যারহাউস সেকশন খুলে নতুন ওয়্যারহাউস যোগ করার অপশন নিন। নাম, যোগাযোগের তথ্য ও পূর্ণ ঠিকানা লিখে যাচাই করার পর সেভ করুন।',
    screenshotIds: ['warehouse-001'],
    source: 'Product Memo §7.2',
  }),
  faq({
    number: 77,
    domain: 'warehouse',
    keywords: ['warehouse', 'edit warehouse', 'delete warehouse', 'ওয়্যারহাউস', 'এডিট'],
    question: 'How do I edit or remove a warehouse?',
    answer: 'Open the warehouse list and use the actions for the warehouse you want to change. Edit and save its details, or choose the available removal action. Review any dependency warning before removing a warehouse used by products or orders.',
    questionBn: 'ওয়্যারহাউস এডিট বা রিমুভ করব কীভাবে?',
    answerBn: 'ওয়্যারহাউস তালিকা থেকে যেটি পরিবর্তন করতে চান তার অ্যাকশন খুলুন। তথ্য এডিট করে সেভ করুন অথবা উপলভ্য রিমুভ অপশন নিন। প্রোডাক্ট বা অর্ডারে ব্যবহৃত ওয়্যারহাউস সরানোর আগে কোনো ডিপেন্ডেন্সি সতর্কতা থাকলে সেটি দেখুন।',
    screenshotIds: ['warehouse-001'],
    source: 'Product Memo §7.2',
  }),
  faq({
    number: 78,
    domain: 'products',
    keywords: ['draft', 'active', 'archived', 'product status', 'ড্রাফট', 'আর্কাইভ'],
    question: 'What do Draft, Active, and Archived product statuses mean?',
    answer: 'Draft products are still being prepared, Active products are ready for supported sales channels, and Archived products are kept out of the active catalogue without losing their saved record.',
    questionBn: 'প্রোডাক্টের Draft, Active ও Archived স্ট্যাটাসের মানে কী?',
    answerBn: 'Draft প্রোডাক্ট এখনো প্রস্তুত হচ্ছে, Active প্রোডাক্ট সমর্থিত সেলস চ্যানেলে ব্যবহারের জন্য প্রস্তুত, আর Archived প্রোডাক্টের রেকর্ড রেখে সেটিকে সক্রিয় ক্যাটালগের বাইরে রাখা হয়।',
    screenshotIds: ['product-001'],
    source: 'Product Memo §7.3',
  }),
  faq({
    number: 79,
    domain: 'products',
    keywords: ['category', 'product category', 'organize products', 'ক্যাটাগরি', 'প্রোডাক্ট'],
    question: 'How should I use product categories?',
    answer: 'Assign the closest relevant category while creating or editing a product. Categories keep the catalogue organized and can support channel mapping, browsing, and reporting.',
    questionBn: 'প্রোডাক্ট ক্যাটাগরি কীভাবে ব্যবহার করব?',
    answerBn: 'প্রোডাক্ট তৈরি বা এডিট করার সময় সবচেয়ে কাছাকাছি প্রাসঙ্গিক ক্যাটাগরি নির্বাচন করুন। ক্যাটাগরি ক্যাটালগ গুছিয়ে রাখে এবং চ্যানেল ম্যাপিং, ব্রাউজিং ও রিপোর্টিংয়ে সহায়তা করতে পারে।',
    screenshotIds: ['product-001'],
    source: 'Product Memo §7.3',
  }),
  faq({
    number: 80,
    domain: 'products',
    keywords: ['duplicate product', 'copy product', 'clone', 'ডুপ্লিকেট', 'কপি'],
    question: 'Can I duplicate an existing product?',
    answer: 'Yes. Use the duplicate action on an existing product to create a copy, then review and change identifiers, variants, price, stock, images, and channel settings before publishing it.',
    questionBn: 'আগের একটি প্রোডাক্ট ডুপ্লিকেট করা যাবে?',
    answerBn: 'হ্যাঁ। আগের প্রোডাক্টের duplicate অ্যাকশন ব্যবহার করে একটি কপি তৈরি করুন। প্রকাশের আগে আইডেন্টিফায়ার, ভ্যারিয়েন্ট, দাম, স্টক, ছবি ও চ্যানেল সেটিংস যাচাই করে প্রয়োজনমতো বদলান।',
    screenshotIds: ['product-001'],
    source: 'Product Memo §7.3',
  }),
  faq({
    number: 81,
    domain: 'products',
    keywords: ['search products', 'filter products', 'catalogue', 'প্রোডাক্ট সার্চ', 'ফিল্টার'],
    question: 'How do I quickly find a product in a large catalogue?',
    answer: 'Use product search with a distinctive name, SKU, or other supported identifier, then narrow the list with the available status, category, stock, or channel filters.',
    questionBn: 'বড় ক্যাটালগে দ্রুত একটি প্রোডাক্ট খুঁজব কীভাবে?',
    answerBn: 'প্রোডাক্ট সার্চে আলাদা করে চেনা যায় এমন নাম, SKU বা সমর্থিত আইডেন্টিফায়ার লিখুন। এরপর উপলভ্য স্ট্যাটাস, ক্যাটাগরি, স্টক বা চ্যানেল ফিল্টার দিয়ে তালিকা ছোট করুন।',
    screenshotIds: ['product-001'],
    source: 'Product Memo §7.3',
  }),
  faq({
    number: 82,
    domain: 'products',
    keywords: ['product images', 'ten images', 'media', 'প্রোডাক্ট ছবি', '১০টি ছবি'],
    question: 'How many images can I add to a product?',
    answer: 'You can add up to 10 images to a product. Choose clear, consistent images from the Media Gallery or upload them while editing the product, then set the most useful image first.',
    questionBn: 'একটি প্রোডাক্টে কয়টি ছবি যোগ করা যায়?',
    answerBn: 'একটি প্রোডাক্টে সর্বোচ্চ ১০টি ছবি যোগ করা যায়। Media Gallery থেকে পরিষ্কার ও সামঞ্জস্যপূর্ণ ছবি নিন অথবা প্রোডাক্ট এডিট করার সময় আপলোড করুন, তারপর সবচেয়ে উপযোগী ছবিটি প্রথমে রাখুন।',
    screenshotIds: ['product-001', 'media-001'],
    source: 'Product Memo §7.3, §7.14',
  }),
  faq({
    number: 83,
    domain: 'products',
    keywords: ['bulk upload', 'csv', 'required columns', 'বাল্ক আপলোড', 'সিএসভি'],
    question: 'Which fields are required for a bulk product CSV upload?',
    answer: 'Download the current bulk-upload template from Pathao Commerce and keep its required columns and headers unchanged. Complete every field marked as required; optional product details can be added where applicable.',
    questionBn: 'বাল্ক প্রোডাক্ট CSV আপলোডে কোন তথ্যগুলো আবশ্যক?',
    answerBn: 'পাঠাও কমার্স থেকে বর্তমান বাল্ক-আপলোড টেমপ্লেট ডাউনলোড করুন এবং এর প্রয়োজনীয় কলাম ও হেডার অপরিবর্তিত রাখুন। required হিসেবে চিহ্নিত প্রতিটি ঘর পূরণ করুন; প্রযোজ্য হলে ঐচ্ছিক প্রোডাক্ট তথ্যও যোগ করতে পারেন।',
    screenshotIds: ['bulk-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 84,
    domain: 'products',
    keywords: ['bulk upload error', 'validation', 'failed rows', 'বাল্ক আপলোড', 'রো ফেল'],
    question: 'Why did some rows fail during bulk product upload?',
    answer: 'Rows fail when required values are missing or data does not match the template rules. Review the validation report, correct only the failed rows without changing the headers, and upload the corrected file again.',
    questionBn: 'বাল্ক প্রোডাক্ট আপলোডে কিছু রো ফেল করেছে কেন?',
    answerBn: 'আবশ্যক তথ্য না থাকলে বা টেমপ্লেটের নিয়মের সঙ্গে ডেটা না মিললে রো ফেল করে। validation report দেখে শুধু ফেল করা রো-গুলো ঠিক করুন, হেডার পরিবর্তন করবেন না, তারপর সংশোধিত ফাইলটি আবার আপলোড করুন।',
    screenshotIds: ['bulk-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 85,
    domain: 'channels',
    keywords: ['daraz category', 'category mapping', 'daraz publish', 'দারাজ', 'ক্যাটাগরি ম্যাপিং'],
    question: 'Why do I need to map a category before publishing to Daraz?',
    answer: 'Daraz requires products to use its own category structure and category-specific attributes. Map your Pathao Commerce product to the closest Daraz category and complete the required attributes before publishing.',
    questionBn: 'Daraz-এ প্রকাশের আগে ক্যাটাগরি ম্যাপ করতে হয় কেন?',
    answerBn: 'Daraz তাদের নিজস্ব ক্যাটাগরি কাঠামো ও ক্যাটাগরি-নির্দিষ্ট তথ্য ব্যবহার করে। প্রকাশের আগে পাঠাও কমার্সের প্রোডাক্টকে সবচেয়ে কাছাকাছি Daraz ক্যাটাগরির সঙ্গে ম্যাপ করে আবশ্যক অ্যাট্রিবিউট পূরণ করুন।',
    screenshotIds: ['daraz-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 86,
    domain: 'inventory',
    keywords: ['stock transfer', 'warehouse transfer', 'inventory', 'স্টক ট্রান্সফার', 'ওয়্যারহাউস'],
    question: 'How do I transfer stock between warehouses?',
    answer: 'Open Inventory, start a stock transfer, choose the source and destination warehouses, select the products and quantities, and confirm the transfer after reviewing it.',
    questionBn: 'এক ওয়্যারহাউস থেকে আরেকটিতে স্টক ট্রান্সফার করব কীভাবে?',
    answerBn: 'Inventory থেকে stock transfer শুরু করুন। source ও destination warehouse নির্বাচন করে প্রোডাক্ট ও পরিমাণ দিন, তারপর তথ্য যাচাই করে ট্রান্সফার নিশ্চিত করুন।',
    screenshotIds: ['inventory-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 87,
    domain: 'inventory',
    keywords: ['inventory sync', 'channel stock', 'stock sync', 'ইনভেন্টরি সিংক', 'স্টক'],
    question: 'How does inventory stay synchronized across channels?',
    answer: 'Pathao Commerce uses its inventory records to coordinate stock for connected, supported channels. Keep product mappings and warehouse stock accurate, and investigate any channel warning before assuming every listing is synchronized.',
    questionBn: 'বিভিন্ন চ্যানেলে ইনভেন্টরি কীভাবে সিংক থাকে?',
    answerBn: 'পাঠাও কমার্সের ইনভেন্টরি রেকর্ড সংযুক্ত ও সমর্থিত চ্যানেলের স্টক সমন্বয় করতে ব্যবহৃত হয়। প্রোডাক্ট ম্যাপিং ও ওয়্যারহাউস স্টক সঠিক রাখুন এবং কোনো চ্যানেল সতর্কতা থাকলে সব লিস্টিং সিংক হয়েছে ধরে নেওয়ার আগে সেটি যাচাই করুন।',
    screenshotIds: ['inventory-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 88,
    domain: 'inventory',
    keywords: ['stock history', 'inventory history', 'adjustment', 'স্টক হিস্ট্রি', 'পরিবর্তন'],
    question: 'Can I see why stock changed?',
    answer: 'Yes. Open the product or inventory history to review recorded stock movements and adjustments, including the available time, reason, source, and change details.',
    questionBn: 'স্টক কেন পরিবর্তন হয়েছে তা দেখা যাবে?',
    answerBn: 'হ্যাঁ। প্রোডাক্ট বা inventory history খুলে রেকর্ড করা stock movement ও adjustment দেখুন। সেখানে উপলভ্য সময়, কারণ, উৎস ও পরিবর্তনের তথ্য পাওয়া যাবে।',
    screenshotIds: ['inventory-001'],
    source: 'Product Memo §7.4',
  }),
  faq({
    number: 89,
    domain: 'channels',
    keywords: ['pathao shop publish', 'publish failed', 'channel error', 'পাঠাও শপ', 'প্রকাশ ব্যর্থ'],
    question: 'Why did publishing a product to Pathao Shop fail?',
    answer: 'Check the channel error and confirm that required product details, images, price, stock, category, and shop connection are complete. Correct the flagged fields and try publishing again.',
    questionBn: 'Pathao Shop-এ প্রোডাক্ট প্রকাশ ব্যর্থ হলে কী করব?',
    answerBn: 'চ্যানেলের error message দেখুন এবং আবশ্যক প্রোডাক্ট তথ্য, ছবি, দাম, স্টক, ক্যাটাগরি ও shop connection সম্পূর্ণ আছে কি না যাচাই করুন। চিহ্নিত ঘরগুলো ঠিক করে আবার প্রকাশ করুন।',
    screenshotIds: ['channels-002'],
    source: 'Product Memo §7.5',
  }),
  faq({
    number: 90,
    domain: 'channels',
    keywords: ['publish daraz', 'daraz listing', 'channel', 'দারাজে প্রকাশ', 'লিস্টিং'],
    question: 'How do I publish a product to Daraz?',
    answer: 'Connect the Daraz shop, select an eligible product, map it to the correct Daraz category, complete all required channel attributes, then submit it for publishing and review the returned status.',
    questionBn: 'Daraz-এ প্রোডাক্ট প্রকাশ করব কীভাবে?',
    answerBn: 'Daraz shop সংযুক্ত করে উপযুক্ত প্রোডাক্ট নির্বাচন করুন। সঠিক Daraz ক্যাটাগরিতে ম্যাপ করে সব আবশ্যক channel attribute পূরণ করুন, তারপর প্রকাশের জন্য submit করে পাওয়া status দেখুন।',
    screenshotIds: ['channels-003'],
    source: 'Product Memo §7.5',
  }),
  faq({
    number: 91,
    domain: 'checkout',
    keywords: ['checkout link', 'share link', 'instant checkout', 'চেকআউট লিংক', 'শেয়ার'],
    question: 'How do I create and share an Instant Checkout link?',
    answer: 'Open Instant Checkout, add the products and order details needed for the link, create it, then copy and share the generated URL with the customer. Review the order in the documented Instant Checkout order location after the customer submits it.',
    questionBn: 'Instant Checkout লিংক তৈরি ও শেয়ার করব কীভাবে?',
    answerBn: 'Instant Checkout খুলে লিংকের জন্য প্রয়োজনীয় প্রোডাক্ট ও অর্ডার তথ্য দিন এবং লিংক তৈরি করুন। তৈরি হওয়া URL কপি করে কাস্টমারকে পাঠান। কাস্টমার সাবমিট করার পর নির্দেশিত Instant Checkout order location-এ অর্ডারটি দেখুন।',
    screenshotIds: ['checkout-001'],
    source: 'Product Memo §7.6',
  }),
  faq({
    number: 92,
    domain: 'orders',
    keywords: ['manual order', 'create order', 'phone order', 'ম্যানুয়াল অর্ডার', 'অর্ডার তৈরি'],
    question: 'Can I create an order manually for a customer?',
    answer: 'Yes. Start a manual order from the order area, add the customer and delivery information, select products and quantities, review charges and payment details, then create the order.',
    questionBn: 'কাস্টমারের জন্য ম্যানুয়ালি অর্ডার তৈরি করা যাবে?',
    answerBn: 'হ্যাঁ। Order সেকশন থেকে manual order শুরু করে কাস্টমার ও ডেলিভারি তথ্য দিন, প্রোডাক্ট ও পরিমাণ নির্বাচন করুন, চার্জ ও পেমেন্ট তথ্য যাচাই করে অর্ডার তৈরি করুন।',
    source: 'Product Memo §7.7',
  }),
  faq({
    number: 93,
    domain: 'orders',
    keywords: ['private note', 'order note', 'internal note', 'প্রাইভেট নোট', 'অর্ডার নোট'],
    question: 'Can I add a private note to an order?',
    answer: 'Yes. Open the order details and add an internal or private note in the available note area. Use it for operational context; it is intended for your team rather than as a customer message.',
    questionBn: 'অর্ডারে প্রাইভেট নোট যোগ করা যাবে?',
    answerBn: 'হ্যাঁ। Order details খুলে উপলভ্য note অংশে internal বা private note যোগ করুন। এটি অপারেশনাল তথ্যের জন্য ব্যবহার করুন; এটি কাস্টমারকে পাঠানো মেসেজ নয়।',
    screenshotIds: ['orders-001'],
    source: 'Product Memo §7.7',
  }),
  faq({
    number: 94,
    domain: 'orders',
    keywords: ['tracking link', 'share tracking', 'order tracking', 'ট্র্যাকিং লিংক', 'অর্ডার ট্র্যাকিং'],
    question: 'How can I share order tracking with a customer?',
    answer: 'Open the order details and use the available tracking information or sharing action for that order. The exact tracking option depends on the order source and delivery setup.',
    questionBn: 'কাস্টমারের সঙ্গে অর্ডার ট্র্যাকিং কীভাবে শেয়ার করব?',
    answerBn: 'Order details খুলে সেই অর্ডারের জন্য উপলভ্য tracking information বা share action ব্যবহার করুন। সঠিক tracking option অর্ডারের উৎস ও delivery setup-এর ওপর নির্ভর করে।',
    screenshotIds: ['orders-001'],
    source: 'Product Memo §7.7',
  }),
  faq({
    number: 95,
    domain: 'delivery',
    keywords: ['instant delivery', 'create delivery', 'delivery request', 'ইনস্ট্যান্ট ডেলিভারি', 'ডেলিভারি তৈরি'],
    question: 'How do I create an Instant Delivery request?',
    answer: 'Open Instant Delivery, enter the pickup and delivery details, add the parcel and recipient information, review the quoted service details, and confirm the request.',
    questionBn: 'Instant Delivery রিকোয়েস্ট তৈরি করব কীভাবে?',
    answerBn: 'Instant Delivery খুলে pickup ও delivery details দিন। parcel ও recipient information যোগ করে দেখানো service details যাচাই করুন, তারপর request নিশ্চিত করুন।',
    screenshotIds: ['delivery-002'],
    source: 'Product Memo §7.9',
  }),
  faq({
    number: 96,
    domain: 'delivery',
    keywords: ['instant delivery tracking', 'delivery status', 'track rider', 'ডেলিভারি ট্র্যাক', 'স্ট্যাটাস'],
    question: 'How do I track an Instant Delivery request?',
    answer: 'Open the Instant Delivery request to review its current status and available tracking details. Follow the status shown in the product; the documentation does not promise a live map or one fixed status sequence for every request.',
    questionBn: 'Instant Delivery রিকোয়েস্ট ট্র্যাক করব কীভাবে?',
    answerBn: 'Instant Delivery request খুলে বর্তমান status ও উপলভ্য tracking details দেখুন। প্রোডাক্টে যে status দেখায় সেটিই অনুসরণ করুন; ডকুমেন্টেশনে প্রতিটি request-এর জন্য live map বা একটিমাত্র নির্দিষ্ট status sequence নিশ্চিত করা হয়নি।',
    screenshotIds: ['delivery-002'],
    source: 'Product Memo §7.9',
  }),
  faq({
    number: 97,
    domain: 'chats',
    keywords: ['quick actions', 'chat order', 'chat product', 'কুইক অ্যাকশন', 'চ্যাট'],
    question: 'What can I do with Quick Actions in a customer chat?',
    answer: 'Quick Actions let you perform supported commerce tasks from the conversation, such as sharing product information or moving into an order-related action, without leaving the chat context.',
    questionBn: 'কাস্টমার চ্যাটের Quick Actions দিয়ে কী করা যায়?',
    answerBn: 'Quick Actions দিয়ে চ্যাটের প্রসঙ্গ না হারিয়ে সমর্থিত কমার্স কাজ করা যায়—যেমন প্রোডাক্ট তথ্য শেয়ার করা বা অর্ডার-সংক্রান্ত অ্যাকশনে যাওয়া।',
    screenshotIds: ['chats-004'],
    source: 'Product Memo §7.9',
  }),
  faq({
    number: 98,
    domain: 'chats',
    keywords: ['quick replies', 'saved reply', 'chat template', 'কুইক রিপ্লাই', 'সেভড রিপ্লাই'],
    question: 'How do Quick Replies help with customer chats?',
    answer: 'Quick Replies let you reuse saved responses for common questions. Choose the closest reply, personalize any customer-specific details, and review it before sending.',
    questionBn: 'Quick Replies কাস্টমার চ্যাটে কীভাবে সাহায্য করে?',
    answerBn: 'Quick Replies দিয়ে সাধারণ প্রশ্নের জন্য সেভ করা উত্তর বারবার ব্যবহার করা যায়। সবচেয়ে প্রাসঙ্গিক উত্তরটি নিন, কাস্টমার-নির্দিষ্ট তথ্য বদলান এবং পাঠানোর আগে যাচাই করুন।',
    screenshotIds: ['chats-004'],
    source: 'Product Memo §7.11',
  }),
  faq({
    number: 99,
    domain: 'addons',
    keywords: ['connection hub', 'addons', 'integration', 'কানেকশন হাব', 'ইন্টিগ্রেশন'],
    question: 'What is the Connection Hub?',
    answer: 'The Connection Hub is where you review and manage supported external connections for Pathao Commerce. Open a connection to see its setup requirements, current state, and available actions.',
    questionBn: 'Connection Hub কী?',
    answerBn: 'Connection Hub হলো পাঠাও কমার্সের সমর্থিত বাহ্যিক connection দেখার ও পরিচালনার জায়গা। কোনো connection খুললে এর setup requirement, বর্তমান অবস্থা ও উপলভ্য action দেখা যায়।',
    screenshotIds: ['addons-001'],
    source: 'Product Memo §7.12',
  }),
  faq({
    number: 100,
    domain: 'addons',
    keywords: ['facebook messenger', 'connect facebook', 'messenger chat', 'ফেসবুক মেসেঞ্জার', 'কানেক্ট'],
    question: 'How do I connect Facebook Messenger?',
    answer: 'Open the Facebook Messenger connection in the Connection Hub, start the authorization flow, sign in to the correct Facebook account, select the intended Page, grant the requested permissions, and confirm the connection status.',
    questionBn: 'Facebook Messenger কীভাবে কানেক্ট করব?',
    answerBn: 'Connection Hub থেকে Facebook Messenger connection খুলে authorization শুরু করুন। সঠিক Facebook account-এ sign in করে প্রয়োজনীয় Page নির্বাচন করুন, চাওয়া permission দিন এবং connection status নিশ্চিত করুন।',
    screenshotIds: ['addons-facebook'],
    source: 'Product Memo §7.12',
  }),
  faq({
    number: 101,
    domain: 'addons',
    keywords: ['whatsapp quick connect', 'whatsapp', 'connect whatsapp', 'হোয়াটসঅ্যাপ', 'কুইক কানেক্ট'],
    question: 'How do I connect WhatsApp with Quick Connect?',
    answer: 'Open WhatsApp in the Connection Hub and choose Quick Connect. Continue through the guided authorization with the correct business account and phone number, grant the requested access, and verify that the connection becomes active.',
    questionBn: 'Quick Connect দিয়ে WhatsApp কীভাবে কানেক্ট করব?',
    answerBn: 'Connection Hub থেকে WhatsApp খুলে Quick Connect বেছে নিন। সঠিক business account ও phone number দিয়ে guided authorization সম্পন্ন করুন, প্রয়োজনীয় access দিন এবং connection active হয়েছে কি না যাচাই করুন।',
    screenshotIds: ['addons-whatsapp-quick'],
    source: 'Product Memo §7.12',
  }),
  faq({
    number: 102,
    domain: 'addons',
    keywords: ['whatsapp manual setup', 'whatsapp business', 'manual connect', 'হোয়াটসঅ্যাপ', 'ম্যানুয়াল সেটআপ'],
    question: 'When should I use WhatsApp Manual Setup?',
    answer: 'Use Manual Setup when your WhatsApp Business configuration requires credentials or identifiers to be entered directly instead of the guided Quick Connect flow. Follow every field shown in the setup screen and verify the connection before using it for customer chats.',
    questionBn: 'WhatsApp Manual Setup কখন ব্যবহার করব?',
    answerBn: 'guided Quick Connect-এর বদলে WhatsApp Business-এর credential বা identifier সরাসরি দিতে হলে Manual Setup ব্যবহার করুন। setup screen-এর প্রতিটি ঘর অনুসরণ করুন এবং কাস্টমার চ্যাটে ব্যবহারের আগে connection যাচাই করুন।',
    screenshotIds: ['addons-whatsapp-manual'],
    source: 'Product Memo §7.12',
  }),
  faq({
    number: 103,
    domain: 'media',
    keywords: ['media gallery', 'upload image', 'reuse image', 'মিডিয়া গ্যালারি', 'ছবি আপলোড'],
    question: 'What is the Media Gallery used for?',
    answer: 'The Media Gallery keeps uploaded images in one place so you can review and reuse them in supported product and store workflows instead of uploading the same file repeatedly.',
    questionBn: 'Media Gallery কী কাজে ব্যবহার হয়?',
    answerBn: 'Media Gallery আপলোড করা ছবি এক জায়গায় রাখে। ফলে একই ফাইল বারবার আপলোড না করে সমর্থিত product ও store workflow-তে ছবি দেখা ও পুনরায় ব্যবহার করা যায়।',
    screenshotIds: ['media-001'],
    source: 'Product Memo §7.14',
  }),
  faq({
    number: 104,
    domain: 'media',
    keywords: ['crop image', 'edit image', 'media gallery', 'ছবি ক্রপ', 'এডিট'],
    question: 'Can I crop an image inside Pathao Commerce?',
    answer: 'Yes. Open the image editing or crop action from the supported media workflow, adjust the crop area, preview the result, and save the edited image before using it.',
    questionBn: 'পাঠাও কমার্সের ভেতরে ছবি crop করা যাবে?',
    answerBn: 'হ্যাঁ। সমর্থিত media workflow থেকে image edit বা crop action খুলুন, crop area ঠিক করে preview দেখুন এবং ব্যবহারের আগে edited image সেভ করুন।',
    screenshotIds: ['media-001'],
    source: 'Product Memo §7.14',
  }),
  faq({
    number: 105,
    domain: 'media',
    keywords: ['link image product', 'product media', 'attach image', 'প্রোডাক্টে ছবি', 'লিংক'],
    question: 'How do I link a Media Gallery image to a product?',
    answer: 'Edit the product, open its image selector, choose the required image from the Media Gallery, arrange it in the desired order, and save the product.',
    questionBn: 'Media Gallery-এর ছবি প্রোডাক্টে যোগ করব কীভাবে?',
    answerBn: 'প্রোডাক্ট এডিট করে image selector খুলুন, Media Gallery থেকে প্রয়োজনীয় ছবি নির্বাচন করুন, পছন্দের ক্রমে সাজিয়ে প্রোডাক্ট সেভ করুন।',
    screenshotIds: ['media-001'],
    source: 'Product Memo §7.14',
  }),
  faq({
    number: 106,
    domain: 'media',
    keywords: ['find media', 'organize images', 'media search', 'ছবি খুঁজুন', 'মিডিয়া সাজান'],
    question: 'How can I find and organize images in the Media Gallery?',
    answer: 'Use the available search, view, and organization controls in the Media Gallery. Give uploaded files meaningful names and review their usage before replacing or removing them.',
    questionBn: 'Media Gallery-তে ছবি খুঁজে ও গুছিয়ে রাখব কীভাবে?',
    answerBn: 'Media Gallery-এর উপলভ্য search, view ও organization control ব্যবহার করুন। আপলোড করা ফাইলের অর্থপূর্ণ নাম দিন এবং কোনো ছবি বদলানো বা সরানোর আগে কোথায় ব্যবহৃত হচ্ছে তা দেখুন।',
    screenshotIds: ['media-001'],
    source: 'Product Memo §7.14',
  }),
  faq({
    number: 107,
    domain: 'online-store',
    keywords: ['store analytics', 'online store', 'traffic', 'স্টোর অ্যানালিটিক্স', 'ভিজিটর'],
    question: 'Where can I review Online Store analytics?',
    answer: 'Open the analytics area for your Online Store to review the metrics currently available for store activity and performance. Use the selected date range and confirm tracking setup when numbers appear incomplete.',
    questionBn: 'Online Store analytics কোথায় দেখব?',
    answerBn: 'Online Store-এর analytics অংশ খুলে বর্তমানে উপলভ্য store activity ও performance metric দেখুন। date range ঠিক আছে কি না দেখুন এবং সংখ্যা অসম্পূর্ণ মনে হলে tracking setup যাচাই করুন।',
    screenshotIds: ['store-analytics'],
    source: 'Product Memo §7.10',
  }),
  faq({
    number: 108,
    domain: 'marketing',
    keywords: ['ad catalogue', 'product feed', 'catalogue', 'অ্যাড ক্যাটালগ', 'প্রোডাক্ট ফিড'],
    question: 'How do I create an ad catalogue?',
    answer: 'Open the ad catalogue workflow, choose the eligible products or catalogue scope, complete the requested channel details, create the catalogue, and use the generated information in the supported advertising platform.',
    questionBn: 'Ad catalogue তৈরি করব কীভাবে?',
    answerBn: 'Ad catalogue workflow খুলে উপযুক্ত প্রোডাক্ট বা catalogue scope নির্বাচন করুন। চাওয়া channel details পূরণ করে catalogue তৈরি করুন এবং তৈরি হওয়া তথ্য সমর্থিত advertising platform-এ ব্যবহার করুন।',
    screenshotIds: ['catalogue-001'],
    source: 'Product Memo §7.10',
  }),
  faq({
    number: 109,
    domain: 'online-store',
    keywords: ['custom page', 'store page', 'about us', 'কাস্টম পেজ', 'অনলাইন স্টোর'],
    question: 'Can I add custom pages to my Online Store?',
    answer: 'Yes. Use the Online Store page-management area to create a page, add its title and content, review its visibility or navigation settings, and publish it when ready.',
    questionBn: 'Online Store-এ custom page যোগ করা যাবে?',
    answerBn: 'হ্যাঁ। Online Store-এর page management অংশ থেকে page তৈরি করুন, title ও content যোগ করুন, visibility বা navigation setting যাচাই করুন এবং প্রস্তুত হলে publish করুন।',
    source: 'Product Memo §7.10',
  }),
  faq({
    number: 110,
    domain: 'online-store',
    keywords: ['meta pixel', 'facebook pixel', 'tracking', 'মেটা পিক্সেল', 'ট্র্যাকিং'],
    question: 'How do I add Meta Pixel tracking to my Online Store?',
    answer: 'Open the Online Store tracking or analytics settings, enter the required Meta Pixel identifier in the supported field, save it, and verify events with Meta tools before relying on campaign reporting.',
    questionBn: 'Online Store-এ Meta Pixel tracking যোগ করব কীভাবে?',
    answerBn: 'Online Store-এর tracking বা analytics settings খুলে সমর্থিত ঘরে প্রয়োজনীয় Meta Pixel identifier দিন এবং সেভ করুন। campaign report-এর ওপর নির্ভর করার আগে Meta-এর tool দিয়ে event যাচাই করুন।',
    screenshotIds: ['store-analytics'],
    source: 'Product Memo §7.12',
  }),
  faq({
    number: 111,
    domain: 'online-store',
    keywords: ['product seo', 'search engine', 'meta title', 'এসইও', 'সার্চ ইঞ্জিন'],
    question: 'How can I improve product SEO for my Online Store?',
    answer: 'Use a clear product title and description, complete the available SEO fields, choose accurate categories, and add useful images. Write for the customer first and avoid repetitive or misleading keywords.',
    questionBn: 'Online Store-এর product SEO কীভাবে উন্নত করব?',
    answerBn: 'পরিষ্কার product title ও description লিখুন, উপলভ্য SEO field পূরণ করুন, সঠিক category নিন এবং উপযোগী ছবি দিন। আগে কাস্টমারের জন্য লিখুন; একই keyword বারবার বা বিভ্রান্তিকরভাবে ব্যবহার করবেন না।',
    source: 'Product Memo §7.3',
  }),
  faq({
    number: 112,
    domain: 'finance',
    keywords: ['finance', 'payment', 'payout', 'transaction', 'ফাইন্যান্স', 'পেমেন্ট'],
    question: 'What can I review in the Finance section?',
    answer: 'Use Finance to review the payment, payout, transaction, and related financial information currently available for your business. Apply the available date or status filters and open a record for details.',
    questionBn: 'Finance সেকশনে কী কী দেখা যায়?',
    answerBn: 'Finance থেকে আপনার ব্যবসার জন্য বর্তমানে উপলভ্য payment, payout, transaction ও সংশ্লিষ্ট আর্থিক তথ্য দেখুন। উপলভ্য date বা status filter ব্যবহার করুন এবং বিস্তারিত জানতে রেকর্ড খুলুন।',
    screenshotIds: ['finance-001'],
    source: 'Product Memo §7.13',
  }),
  faq({
    number: 113,
    domain: 'finance',
    keywords: ['fees', 'commission', 'charges', 'ফি', 'কমিশন', 'চার্জ'],
    question: 'Where can I confirm Pathao Commerce fees or commission?',
    answer: 'The Product Memo does not define one universal fee or commission schedule. Review the applicable amount in Finance, the relevant service or channel screen, and your current commercial terms; contact Pathao support if those sources do not resolve it.',
    questionBn: 'পাঠাও কমার্সের ফি বা কমিশন কোথায় নিশ্চিত করব?',
    answerBn: 'Product Memo-তে সবার জন্য একটিমাত্র fee বা commission schedule নির্ধারিত নেই। Finance, সংশ্লিষ্ট service বা channel screen এবং আপনার বর্তমান commercial terms দেখুন; সেখানেও পরিষ্কার না হলে পাঠাও সাপোর্টে যোগাযোগ করুন।',
    screenshotIds: ['finance-001'],
    source: 'Product Memo §7.13',
  }),
] satisfies KnowledgeItem[];
