import type { KnowledgeItem } from './knowledgeBase';

const PLAYLIST_ID = 'PLMN1y8VZcPd8';

function videoSource(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}&list=${PLAYLIST_ID}`;
}

/**
 * Task-focused guides reviewed against every video in Pathao's official Commerce
 * tutorial playlist. The summaries are intentionally narrower than the product
 * memo: they describe only the flow demonstrated in each linked video.
 */
export const TUTORIAL_VIDEO_ITEMS = [
  {
    id: 'tutorial-video-001',
    feature: 'Video: Publish products to Pathao Shop',
    domain: 'channels',
    keywords: ['tutorial video', 'pathao shop', 'publish products', 'bulk publish', 'preview', 'পাঠাও শপ', 'প্রোডাক্ট পাবলিশ'],
    question: 'How do I publish products to Pathao Shop?',
    answer: 'A Pathao Shop account is created with the Commerce account. Open Products, select one or more products, choose Publish on Pathao Shop, review or edit the preview, and publish. The same action is also available from the Pathao Shop section.',
    steps: [
      'Open Pathao Shop to review or edit the automatically created shop profile.',
      'Open Products and select the products to publish; use select all when needed.',
      'Click Publish on Pathao Shop.',
      'Review the preview and edit any details that need correction.',
      'Click Publish and confirm that the products are available in Pathao Shop.',
    ],
    status: 'live',
    source: videoSource('-Gup_tswNK8'),
    screenshotIds: ['channels-001', 'channels-002'],
    translations: {
      bn: {
        question: 'পাঠাও শপে প্রোডাক্ট পাবলিশ করব কীভাবে?',
        answer: 'Commerce অ্যাকাউন্ট তৈরির সময় একটি Pathao Shop অ্যাকাউন্টও তৈরি হয়। Products থেকে এক বা একাধিক প্রোডাক্ট নির্বাচন করে Publish on Pathao Shop চাপুন, preview দেখে প্রয়োজন হলে তথ্য ঠিক করুন, তারপর Publish করুন। Pathao Shop সেকশন থেকেও একই কাজ করা যায়।',
      },
    },
  },
  {
    id: 'tutorial-video-002',
    feature: 'Video: Manage inventory and stock',
    domain: 'inventory',
    keywords: ['tutorial video', 'inventory', 'stock', 'warehouse stock', 'variant stock', 'low stock', 'out of stock', 'ইনভেন্টরি', 'স্টক'],
    question: 'How do I update inventory and stock in Pathao Commerce?',
    answer: 'Open a product from Products and use its Inventory action. In the side sheet, choose the warehouse or variant whose quantity needs changing, enter the updated stock value, and save the inventory update.',
    steps: [
      'Open Products from the dashboard.',
      'Choose the Inventory action for the product you want to update.',
      'In the side sheet, select the relevant warehouse or product variant.',
      'Enter the new stock value, including corrections for low-stock or out-of-stock items.',
      'Click Update Inventory and verify the new quantity.',
    ],
    status: 'live',
    source: videoSource('fpGiYW3a9Og'),
    screenshotIds: ['inventory-001'],
    translations: {
      bn: {
        question: 'পাঠাও কমার্সে ইনভেন্টরি ও স্টক আপডেট করব কীভাবে?',
        answer: 'Products থেকে প্রোডাক্টটির Inventory action খুলুন। পাশের sheet-এ প্রয়োজনীয় warehouse বা variant নির্বাচন করে নতুন stock quantity লিখুন, তারপর Update Inventory দিয়ে পরিবর্তনটি সেভ করুন।',
      },
    },
  },
  {
    id: 'tutorial-video-003',
    feature: 'Video: Create and publish an Online Store',
    domain: 'store',
    keywords: ['tutorial video', 'online store', 'create store', 'publish store', 'branding', 'theme', 'guest checkout', 'pixel', 'catalogue', 'অনলাইন স্টোর'],
    question: 'How do I create, customize, and publish an Online Store?',
    answer: 'Create the store with a name, subdomain, and pickup warehouse, then use Manage Website to add business details, branding, layout, theme, social links, and policies. Turn on the publish setting when the store is ready. Tracking and ad-catalogue options can be configured afterward.',
    steps: [
      'Open Online Store and start creating a store.',
      'Enter the store name and subdomain, choose a pickup warehouse, and save.',
      'Open Manage Website and add the description, contact number, and guest-checkout preference.',
      'Upload the logo and banner, then choose the website layout and theme.',
      'Add supported social contact details and the return and refund policies.',
      'Turn on the publish setting and save, then use Visit Website to check the live store.',
      'Add Pixel and tracking information if customer activity measurement is needed.',
      'Create an ad catalogue and copy its link to Meta Business Manager if required.',
    ],
    status: 'live',
    source: videoSource('pnNK5kneHzY'),
    screenshotIds: ['store-001', 'store-analytics', 'catalogue-001'],
    translations: {
      bn: {
        question: 'Online Store তৈরি, সাজানো ও publish করব কীভাবে?',
        answer: 'স্টোরের নাম, subdomain ও pickup warehouse দিয়ে Online Store তৈরি করুন। এরপর Manage Website থেকে business details, branding, layout, theme, social links ও policy যোগ করুন। সব ঠিক হলে publish setting চালু করে save করুন; প্রয়োজন হলে পরে tracking ও ad catalogue সেট করুন।',
      },
    },
  },
  {
    id: 'tutorial-video-004',
    feature: 'Video: Create a single product and variants',
    domain: 'products',
    keywords: ['tutorial video', 'single product', 'create product', 'sku', 'variant', 'attribute', 'size', 'product image', 'সিংগেল প্রোডাক্ট', 'ভ্যারিয়েন্ট'],
    question: 'How do I create a single product with variants?',
    answer: 'Start from Products → Create Product. Add the core product details, pricing and shipping information, and images. If the product has choices such as sizes, add an attribute and its values, then review the generated variants, their images, and stock before saving.',
    steps: [
      'Open Products and click Create Product.',
      'Enter the product name and category, base SKU, and initial stock.',
      'Add the description and size chart when applicable.',
      'Enter the price, any discount, base weight, and dimensions.',
      'Upload product images from the Media Gallery.',
      'For variations, click Add Attribute and enter values such as sizes.',
      'Review each generated variant, including its image and stock quantity.',
      'Save the completed product profile.',
    ],
    status: 'live',
    source: videoSource('2fwaZhpNOZk'),
    screenshotIds: ['product-001', 'media-001'],
    translations: {
      bn: {
        question: 'ভ্যারিয়েন্টসহ একটি single product তৈরি করব কীভাবে?',
        answer: 'Products → Create Product থেকে নাম, category, SKU, initial stock, description, price, discount, weight, dimensions ও ছবি দিন। size-এর মতো variation থাকলে Add Attribute থেকে value যোগ করুন, তৈরি হওয়া প্রতিটি variant-এর ছবি ও stock যাচাই করে Save করুন।',
      },
    },
  },
  {
    id: 'tutorial-video-005',
    feature: 'Video: Connect Facebook',
    domain: 'chats',
    keywords: ['tutorial video', 'facebook', 'messenger', 'meta', 'business page', 'business portfolio', 'connect facebook', 'ফেসবুক কানেক্ট'],
    question: 'How do I connect Facebook to Pathao Commerce?',
    answer: 'Open Chats and start Connect Facebook. Sign in to Facebook, review the connection settings, select the correct business Page and Meta Business Portfolio, grant the requested access, and save. You can also start the same connection from Integrations.',
    prerequisites: ['Access to the Facebook account, business Page, and Meta Business Portfolio being connected'],
    steps: [
      'Open Chats and click Connect Facebook.',
      'Sign in with the Facebook account that manages the business Page.',
      'Review or edit the connection settings.',
      'Select the intended business Page and Meta Business Portfolio.',
      'Review the requested permissions and save the connection.',
      'Confirm that Facebook is active in Chats or Integrations.',
    ],
    status: 'live',
    source: videoSource('okLbyhWQBdc'),
    screenshotIds: ['addons-facebook', 'chats-001'],
    translations: {
      bn: {
        question: 'পাঠাও কমার্সে Facebook কানেক্ট করব কীভাবে?',
        answer: 'Chats থেকে Connect Facebook চাপুন। সঠিক Facebook account-এ login করে business Page ও Meta Business Portfolio নির্বাচন করুন, চাওয়া permission review করে connection save করুন। Integrations থেকেও একই flow শুরু করা যায়।',
      },
    },
  },
  {
    id: 'tutorial-video-006',
    feature: 'Video: Connect WhatsApp',
    domain: 'chats',
    keywords: ['tutorial video', 'whatsapp', 'whatsapp business', 'meta business portfolio', 'qr code', 'timezone', 'হোয়াটসঅ্যাপ কানেক্ট'],
    question: 'How do I connect a WhatsApp Business account?',
    answer: 'From Chats, start Connect WhatsApp and continue only with a WhatsApp Business account and Meta Business Portfolio. Complete Meta authentication, choose or connect the business account and phone number, scan the QR code, follow the WhatsApp instructions, select the timezone, review, confirm, and finish.',
    prerequisites: ['WhatsApp Business account', 'Meta Business Portfolio', 'Access to the WhatsApp phone being connected'],
    steps: [
      'Open Chats and click Connect WhatsApp.',
      'Confirm that a WhatsApp Business account and Meta Business Portfolio are available.',
      'Complete Meta authentication and continue.',
      'Select the shown portfolio and WhatsApp Business account, or choose Connect a WhatsApp Business App.',
      'Enter the phone number and review the requested access.',
      'Scan the QR code with the WhatsApp Business app and follow its instructions.',
      'Select the timezone, review the connection, and confirm.',
      'Click Finish and verify the active connection; Integrations offers the same flow.',
    ],
    status: 'live',
    source: videoSource('zUYW9WlcDtQ'),
    screenshotIds: ['addons-whatsapp-quick', 'chats-001'],
    translations: {
      bn: {
        question: 'WhatsApp Business account কানেক্ট করব কীভাবে?',
        answer: 'Chats থেকে Connect WhatsApp শুরু করুন। Meta authentication শেষ করে business portfolio ও WhatsApp Business account নির্বাচন করুন বা নতুন app connect করুন। phone number দিন, access review করুন, WhatsApp Business app দিয়ে QR code scan করুন, timezone বেছে review ও confirm করে Finish চাপুন।',
      },
    },
  },
  {
    id: 'tutorial-video-007',
    feature: 'Video: Sign up for Pathao Commerce',
    domain: 'signup',
    keywords: ['tutorial video', 'signup', 'manual signup', 'courier account', 'google account', 'otp', 'warehouse', 'সাইন আপ'],
    question: 'What signup methods can I use for Pathao Commerce?',
    answer: 'The tutorial shows three choices: manual signup, a Pathao Courier account, or a Google account. Manual signup starts with email, then asks for the business name, mobile number, warehouse, and password before OTP verification. Matching Courier information and warehouses may be imported automatically.',
    steps: [
      'Open the Pathao Commerce site and click Get Started for Free or Sign Up.',
      'Choose manual signup, Pathao Courier, or Google.',
      'For manual signup, continue with an email address.',
      'Enter the business name, mobile number, warehouse, and password.',
      'Verify the OTP to complete signup.',
      'If a matching Courier account is detected, review the imported account and warehouse information.',
    ],
    status: 'live',
    source: videoSource('weYyy08MafM'),
    screenshotIds: ['signup-001', 'signup-002', 'signup-003'],
    translations: {
      bn: {
        question: 'পাঠাও কমার্সে কোন কোনভাবে sign up করা যায়?',
        answer: 'ভিডিওতে তিনটি উপায় দেখানো হয়েছে: manual signup, Pathao Courier account এবং Google account। Manual signup-এ email দিয়ে শুরু করে business name, mobile number, warehouse ও password দিন, তারপর OTP verify করুন। একই email-এর Courier account পাওয়া গেলে তার তথ্য ও warehouse স্বয়ংক্রিয়ভাবে যোগ হতে পারে।',
      },
    },
  },
  {
    id: 'tutorial-video-008',
    feature: 'Video: Bulk upload products with CSV',
    domain: 'products',
    keywords: ['tutorial video', 'bulk upload', 'import products', 'csv', 'warehouse', 'column mapping', 'প্রোডাক্ট বাল্ক আপলোড'],
    question: 'How do I bulk upload products from a CSV file?',
    answer: 'Open Products → Import Products, choose CSV as the source, select the warehouse, and upload the file. Review the column mapping, correct any product information that needs attention, then run the import.',
    steps: [
      'Open Products and click Import Products.',
      'Choose CSV as the source and select the destination warehouse.',
      'Click Next, upload the CSV file, and continue.',
      'Review every mapped column before proceeding.',
      'Correct any product information flagged for manual attention.',
      'Click Import and confirm that the products appear in Commerce.',
    ],
    status: 'live',
    source: videoSource('jq5rHfRStjs'),
    screenshotIds: ['bulk-001'],
    translations: {
      bn: {
        question: 'CSV দিয়ে একসাথে অনেক প্রোডাক্ট upload করব কীভাবে?',
        answer: 'Products → Import Products খুলে source হিসেবে CSV এবং প্রয়োজনীয় warehouse নির্বাচন করুন। file upload করে সব column mapping যাচাই করুন, দরকার হলে product information ঠিক করুন, তারপর Import চাপুন।',
      },
    },
  },
  {
    id: 'tutorial-video-009',
    feature: 'Video: Connect Daraz and import products',
    domain: 'channels',
    keywords: ['tutorial video', 'daraz', 'connect daraz', 'import products', 'warehouse', 'category mapping', 'দারাজ কানেক্ট', 'প্রোডাক্ট ইম্পোর্ট'],
    question: 'How do I connect Daraz and import its products?',
    answer: 'Connect the Daraz shop first, then open Products → Import Products, select Daraz and the destination warehouse, fetch and select the products, review category mapping and validation, and import them into Commerce.',
    prerequisites: ['Access to the Daraz seller account being connected', 'A destination warehouse in Pathao Commerce'],
    steps: [
      'Open the Daraz connection from the dashboard and authorize the intended seller account.',
      'Open Products and click Import Products.',
      'Select Daraz as the source and choose the destination warehouse.',
      'Fetch the products and select the items to import.',
      'Review or complete category mapping and validation.',
      'Click Import and verify the imported products in Commerce.',
    ],
    status: 'live',
    source: videoSource('lngsxYOaWDY'),
    screenshotIds: ['addons-daraz', 'daraz-001'],
    translations: {
      bn: {
        question: 'Daraz কানেক্ট করে প্রোডাক্ট import করব কীভাবে?',
        answer: 'প্রথমে সঠিক Daraz seller account connect করুন। তারপর Products → Import Products থেকে source হিসেবে Daraz ও destination warehouse বেছে product fetch করুন। প্রয়োজনীয় product নির্বাচন করে category mapping ও validation যাচাই করুন, তারপর Import চাপুন।',
      },
    },
  },
  {
    id: 'tutorial-video-010',
    feature: 'Video: Create and share an Instant Checkout link',
    domain: 'checkout',
    keywords: ['tutorial video', 'instant checkout', 'checkout link', 'generate link', 'share link', 'social media', 'ইন্সট্যান্ট চেকআউট'],
    question: 'How do I create and share an Instant Checkout link?',
    answer: 'Start Instant Checkout from the header, a product card, or a chat. Add an existing or custom product, confirm quantity, price, weight, and warehouse details, add the item to the cart, generate the link, and share it in social posts, comments, captions, or messages.',
    steps: [
      'Open Instant Checkout from the header, a product card, or a customer chat.',
      'Search for an existing product or create a custom product.',
      'Set the quantity, unit price, weight, and warehouse as required.',
      'Add the item to the cart and review the summary.',
      'Click Generate Link.',
      'Copy and share the link through the appropriate social post, comment, caption, or message.',
    ],
    status: 'live',
    source: videoSource('FqyB81niqsQ'),
    screenshotIds: ['checkout-001'],
    translations: {
      bn: {
        question: 'Instant Checkout link তৈরি ও share করব কীভাবে?',
        answer: 'Header, product card বা chat থেকে Instant Checkout খুলুন। existing বা custom product যোগ করে quantity, unit price, weight ও warehouse যাচাই করুন, cart-এ যোগ করে Generate Link চাপুন। তৈরি link social post, comment, caption বা message-এ share করতে পারবেন।',
      },
    },
  },
  {
    id: 'tutorial-video-011',
    feature: 'Video: Manage payments, payouts, and invoices',
    domain: 'finance',
    keywords: ['tutorial video', 'payment', 'payout', 'payout method', 'bank', 'mobile banking', 'transaction', 'invoice', 'পেমেন্ট', 'পেআউট', 'ইনভয়েস'],
    question: 'How do I set up payouts and review payments and invoices?',
    answer: 'Add a payout method from Settings by choosing bank or mobile banking and completing the required information. In Finance, review totals and transaction details by order and channel, and open Invoices to inspect or download received invoices.',
    steps: [
      'Open Settings and click Add Payout Method.',
      'Choose bank or mobile banking and complete the required information.',
      'Save the payout method.',
      'Open Finance from the sidebar to review total payment information.',
      'Use Transactions to inspect order, channel, delivery, and payment details.',
      'Use Invoices to review received payments and download a detailed invoice.',
    ],
    status: 'live',
    source: videoSource('VtY7tRxHQwk'),
    screenshotIds: ['finance-001'],
    translations: {
      bn: {
        question: 'Payment, payout ও invoice manage করব কীভাবে?',
        answer: 'Settings থেকে Add Payout Method খুলে bank বা mobile banking বেছে প্রয়োজনীয় তথ্য দিয়ে save করুন। এরপর Finance থেকে total payment দেখুন, Transactions-এ order ও channel অনুযায়ী details যাচাই করুন এবং Invoices থেকে প্রাপ্ত invoice খুলুন বা download করুন।',
      },
    },
  },
  {
    id: 'tutorial-video-012',
    feature: 'Video: Create and select a warehouse',
    domain: 'warehouse',
    keywords: ['tutorial video', 'warehouse', 'create warehouse', 'contact', 'address', 'city zone area', 'approval pending', 'default warehouse', 'ওয়্যারহাউস'],
    question: 'How do I create and select a warehouse?',
    answer: 'Open Warehouses and choose Create Warehouse. Enter the warehouse name, contact name, phone numbers, full address, and city, zone, and area, then save. Newly created warehouses are reviewed by the courier team; after approval, review the list and set the appropriate warehouse as default.',
    steps: [
      'Open Warehouses from the dashboard sidebar.',
      'Click Create Warehouse.',
      'Enter the warehouse name and contact name.',
      'Add the phone number, optional alternate phone number, and full address.',
      'Select the city, zone, and area, then save.',
      'Wait for courier-team approval and check the status in the warehouse list.',
      'After approval, set the appropriate warehouse as default or edit its settings when needed.',
    ],
    status: 'live-with-dependency',
    source: videoSource('I95Sd5MCVD8'),
    screenshotIds: ['warehouse-001'],
    translations: {
      bn: {
        question: 'নতুন warehouse তৈরি ও select করব কীভাবে?',
        answer: 'Warehouses থেকে Create Warehouse চাপুন। warehouse name, contact name, phone number, পূর্ণ address এবং city, zone ও area দিয়ে Save করুন। নতুন warehouse courier team approve করবে; approval হওয়ার পর তালিকা থেকে প্রয়োজনীয় warehouse default হিসেবে সেট করতে পারবেন।',
      },
    },
  },
  {
    id: 'tutorial-video-013',
    feature: 'Video: Create an Instant Delivery order',
    domain: 'delivery',
    keywords: ['tutorial video', 'instant delivery', 'create order', 'pickup', 'recipient', 'sender pays', 'receiver pays', 'selling something', 'bKash', 'ইন্সট্যান্ট ডেলিভারি'],
    question: 'How do I place and track an Instant Delivery order?',
    answer: 'Open Instant Delivery → Create Order, complete pickup, sender, recipient, and address details, then choose an available delivery option. Select who pays, add item or collection information when applicable, review and place the order, and follow its status from Active Orders.',
    steps: [
      'Open Instant Delivery from the dashboard sidebar and click Create Order.',
      'Complete the pickup, sender, recipient, and customer details.',
      'Choose a warehouse or another supported pickup location.',
      'Select one of the delivery options available for the entered addresses.',
      'Choose whether the sender or receiver pays.',
      'Enter the item value; when collecting an order payment, turn on Selling Something, add the item price, and provide the supported payout number.',
      'Click Review Order and verify all details.',
      'Click Confirm and Place Order, then open the order in Active Orders to review Status History.',
    ],
    status: 'live',
    source: videoSource('RTYd4bdKMxk'),
    screenshotIds: ['delivery-002'],
    translations: {
      bn: {
        question: 'Instant Delivery order তৈরি ও track করব কীভাবে?',
        answer: 'Instant Delivery → Create Order থেকে pickup, sender, recipient ও address details পূরণ করে উপলভ্য delivery option বাছুন। sender না receiver কে payment করবে তা নির্বাচন করুন; প্রয়োজন হলে item value বা collection information দিন। Review Order দেখে Confirm and Place Order চাপুন, তারপর Active Orders-এর Status History থেকে track করুন।',
      },
    },
  },
  {
    id: 'tutorial-video-014',
    feature: 'Video: Connect Instagram',
    domain: 'chats',
    keywords: ['tutorial video', 'instagram', 'connect instagram', 'permissions', 'allow access', 'integrations', 'ইন্সটাগ্রাম কানেক্ট'],
    question: 'How do I connect Instagram to Pathao Commerce?',
    answer: 'Open Chats and start Connect Instagram. Sign in to the intended Instagram account, review the connection permissions, allow the requested access, and return to Commerce to confirm the account is connected. The same connection can also be managed from Integrations.',
    prerequisites: ['Login access to the Instagram account being connected'],
    steps: [
      'Open Chats and click Connect Instagram.',
      'Sign in to the intended Instagram account.',
      'Review the connection and permission toggles.',
      'Allow the requested access.',
      'Return to Pathao Commerce and verify the connected account in Chats or Integrations.',
    ],
    status: 'live',
    source: videoSource('mWQHsZh2rwk'),
    screenshotIds: ['chats-001'],
    translations: {
      bn: {
        question: 'পাঠাও কমার্সে Instagram কানেক্ট করব কীভাবে?',
        answer: 'Chats থেকে Connect Instagram চাপুন। সঠিক Instagram account-এ login করে connection permission review করুন এবং প্রয়োজনীয় access Allow করুন। Commerce-এ ফিরে account connected হয়েছে কি না যাচাই করুন; Integrations থেকেও connection manage করা যায়।',
      },
    },
  },
] satisfies KnowledgeItem[];
